import nlp from "compromise";

const stopWords = new Set([
    "hackathons",
    "coding competitions",
    "programming contests",
    "tech talks",
    "workshops",
    "seminars",
    "conferences",
    "tech fest",
    "technology festival",
    "innovation",
    "robotics",
    "automation",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural networks",
    "computer vision",
    "data science",
    "big data",
    "analytics",
    "algorithms",
    "data structures",
    "software engineering",
    "web development",
    "mobile development",
    "app development",
    "full stack",
    "frontend",
    "backend",
    "database",
    "cloud computing",
    "devops",
    "cybersecurity",
    "blockchain",
    "cryptocurrency",
    "web3",
    "iot",
    "internet of things",
    "embedded systems",
    "microcontrollers",
    "arduino",
    "raspberry pi",
    "sensors",
    "drone technology",
    "3d printing",
    "virtual reality",
    "augmented reality",
    "mixed reality",
    "gaming",
    "game development",
    "unity",
    "unreal engine",
    "programming languages",
    "python",
    "java",
    "javascript",
    "c++",
    "go",
    "rust",
    "kotlin",
    "swift",
    "frameworks",
    "react",
    "angular",
    "vue",
    "node.js",
    "django",
    "flask",
    "spring boot",
    "docker",
    "kubernetes",
    "microservices",
    "api development",
    "rest api",
    "graphql",
    "git",
    "version control",
    "agile",
    "scrum",
    "startup",
    "entrepreneurship",
    "pitch competition",
    "business model",
    "mvp",
    "product development",
    "ui design",
    "ux design",
    "design thinking",
    "prototyping",
    "wireframing",
    "figma",
    "cultural events",
    "dance",
    "music",
    "stage performances",
    "cultural shows",
    "folk dance",
    "classical dance",
    "western dance",
    "hip hop",
    "bollywood",
    "fusion dance",
    "group dance",
    "solo dance",
    "choreography",
    "dance battles",
    "music competitions",
    "singing",
    "band performances",
    "dj",
    "electronic music",
    "live music",
    "concerts",
    "acoustic sessions",
    "karaoke",
    "beatboxing",
    "rap battles",
    "poetry",
    "slam poetry",
    "open mic",
    "storytelling",
    "drama",
    "theater",
    "acting",
    "skits",
    "stand up comedy",
    "improv",
    "mime",
    "street performances",
    "flash mobs",
    "fashion shows",
    "ramp walk",
    "modeling",
    "costume competitions",
    "art exhibitions",
    "painting",
    "sketching",
    "photography",
    "digital art",
    "sculpture",
    "crafts",
    "diy workshops",
    "sports",
    "esports",
    "gaming tournaments",
    "outdoor games",
    "indoor games",
    "team sports",
    "individual sports",
    "athletics",
    "marathon",
    "cycling",
    "adventure sports",
    "accommodation",
    "hostel",
    "guest house",
    "hotels",
    "dormitory",
    "shared rooms",
    "single rooms",
    "double rooms",
    "triple rooms",
    "ac rooms",
    "non ac rooms",
    "mess facility",
    "food arrangements",
    "breakfast",
    "lunch",
    "dinner",
    "snacks",
    "refreshments",
    "catering",
    "food stalls",
    "cafeteria",
    "canteen",
    "dining hall",
    "vegetarian",
    "non vegetarian",
    "vegan",
    "jain food",
    "regional cuisine",
    "street food",
    "registration",
    "participate",
    "enrollment",
    "entry fee",
    "registration fee",
    "early bird",
    "spot registration",
    "team registration",
    "individual registration",
    "group registration",
    "online registration",
    "offline registration",
    "payment",
    "payment methods",
    "cash",
    "online payment",
    "upi",
    "card payment",
    "net banking",
    "wallet",
    "refund policy",
    "cancellation",
    "schedule",
    "timetable",
    "agenda",
    "event timeline",
    "program schedule",
    "day wise events",
    "time slots",
    "duration",
    "start time",
    "end time",
    "venue",
    "location",
    "auditorium",
    "seminar hall",
    "conference room",
    "classroom",
    "laboratory",
    "ground",
    "playground",
    "sports complex",
    "gymnasium",
    "stage",
    "main stage",
    "open air theater",
    "amphitheater",
    "campus",
    "college",
    "nit rourkela",
    "national institute of technology",
    "rourkela",
    "odisha",
    "hostel blocks",
    "academic blocks",
    "departments",
    "library",
    "mess",
    "medical center",
    "student activity center",
    "innovation center",
    "incubation center",
    "research labs",
    "transport",
    "bus facility",
    "shuttle service",
    "parking",
    "local transport",
    "railway station",
    "airport",
    "cab service",
    "auto rickshaw",
    "cycle",
    "walking distance",
    "directions",
    "map",
    "landmarks",
    "contact",
    "phone number",
    "email",
    "website",
    "social media",
    "facebook",
    "instagram",
    "twitter",
    "linkedin",
    "youtube",
    "telegram",
    "whatsapp",
    "coordinators",
    "organizing committee",
    "volunteers",
    "student coordinators",
    "faculty coordinators",
    "mentors",
    "judges",
    "guests",
    "chief guests",
    "keynote speakers",
    "industry experts",
    "alumni",
    "sponsors",
    "partners",
    "collaborators",
    "certificates",
    "prizes",
    "awards",
    "trophies",
    "medals",
    "cash prizes",
    "gift vouchers",
    "goodies",
    "swag",
    "t shirts",
    "bags",
    "stickers",
    "badges",
    "id cards",
    "lanyards",
    "wristbands",
    "rules",
    "regulations",
    "guidelines",
    "eligibility",
    "age limit",
    "student verification",
    "college id",
    "dress code",
    "code of conduct",
    "safety measures",
    "security",
    "first aid",
    "emergency contacts",
    "lost and found",
    "help desk",
    "information desk",
    "queries",
    "complaints",
    "feedback",
    "suggestions",
    "social events",
    "networking",
    "meetups",
    "panel discussions",
    "fireside chats",
    "interactive sessions",
    "q&a sessions",
    "exhibitions",
    "project exhibitions",
    "poster presentations",
    "demo sessions",
    "startup showcase",
    "innovation fair",
    "tech expo"
]

);

export default function extractKeywords(sentence) {
    const doc = nlp(sentence);
    const terms = doc.terms().out("array");
    const keywords = terms.filter((word) => !stopWords.has(word.toLowerCase()));
    return keywords;
}